/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.Arrays;
import javax.swing.JOptionPane;
import metodes.metodeGUI;
import projecte.Serie;
import projecte.Projecte;
import static projecte.Projecte.MAX_SERIES;
import static projecte.Projecte.getArray;

/**
 *
 * @author fbonet
 */
public class GUI_projecte extends javax.swing.JFrame {

    private static int filaActual = -1;
    private int casellaBuida = -1;

    public GUI_projecte() {
        initComponents();
        inicialitzarComponents();
    }

    private void inicialitzarComponents() {
        buttonEliminar.setEnabled(false);
        buttonModificar.setEnabled(false);
        checkBoxAcabat.setSelected(true);
        casellaBuida = Projecte.inicialitzarVariables();
        reiniciarFormulari();
    }

    public static Object[][] transformarDades(Serie[] dades) {
        Object[][] resultat = new Object[dades.length][9];
        int omplert = 0;
        for (int i = 0; i < dades.length; i++) {
            if (dades[i].isOmplert()) {
                resultat[omplert][0] = i;
                resultat[omplert][1] = dades[i].getNom();
                resultat[omplert][2] = dades[i].getGenere();
                resultat[omplert][3] = dades[i].getDescripcio();
                resultat[omplert][4] = dades[i].getNumCapitols();
                resultat[omplert][5] = dades[i].getDuracioCapitols();
                resultat[omplert][6] = dades[i].getAnyEmissio();
                resultat[omplert][7] = dades[i].getNota();
                resultat[omplert][8] = dades[i].isAcabat();
                omplert++;
            }
        }
        return Arrays.copyOf(resultat, omplert);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitol = new javax.swing.JLabel();
        scrollPaneTaula = new javax.swing.JScrollPane();
        tableDades = new javax.swing.JTable();
        labelNom = new javax.swing.JLabel();
        textFieldNom = new javax.swing.JTextField();
        labelGenere = new javax.swing.JLabel();
        textFieldGenere = new javax.swing.JTextField();
        labelDescripcio = new javax.swing.JLabel();
        textFieldDescripcio = new javax.swing.JTextField();
        labelNumCapitols = new javax.swing.JLabel();
        textFieldNumCapitols = new javax.swing.JTextField();
        labelDuracioCapitols = new javax.swing.JLabel();
        textFieldDuracioCapitols = new javax.swing.JTextField();
        labelAnyEmissio = new javax.swing.JLabel();
        textFieldAnyEmissio = new javax.swing.JTextField();
        labelNota = new javax.swing.JLabel();
        textFieldNota = new javax.swing.JTextField();
        labelAcabat = new javax.swing.JLabel();
        checkBoxAcabat = new javax.swing.JCheckBox();
        buttonInserir = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonSortir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelTitol.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        labelTitol.setText("Sèries");

        tableDades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDadesMouseClicked(evt);
            }
        });
        scrollPaneTaula.setViewportView(tableDades);

        labelNom.setText("Nom");

        labelGenere.setText("Genere");

        labelDescripcio.setText("Descripció");

        labelNumCapitols.setText("Número de capítols");

        labelDuracioCapitols.setText("Duració capítols");

        labelAnyEmissio.setText("Any d'emissió");

        labelNota.setText("Nota");

        labelAcabat.setText("Acabat");

        buttonInserir.setText("Inserir");
        buttonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserirActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonSortir.setText("Sortir");
        buttonSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTaula, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNumCapitols, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(labelDuracioCapitols, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelAnyEmissio, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelNota, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(labelAcabat)
                    .addComponent(labelGenere)
                    .addComponent(labelDescripcio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxAcabat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textFieldDescripcio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(textFieldGenere, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldAnyEmissio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldDuracioCapitols, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNumCapitols, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(labelTitol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonInserir)
                .addGap(18, 18, 18)
                .addComponent(buttonModificar)
                .addGap(18, 18, 18)
                .addComponent(buttonEliminar)
                .addGap(18, 18, 18)
                .addComponent(buttonSortir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonInserir)
                            .addComponent(buttonModificar)
                            .addComponent(buttonEliminar)
                            .addComponent(buttonSortir))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNom, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(textFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGenere, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldGenere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldDescripcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDescripcio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumCapitols, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNumCapitols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDuracioCapitols, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDuracioCapitols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAnyEmissio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldAnyEmissio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNota, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkBoxAcabat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAcabat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(scrollPaneTaula, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableDadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDadesMouseClicked
        filaActual = tableDades.getSelectedRow();
        if (filaActual == -1) {
            reiniciarFormulari();
        } else {
            buttonEliminar.setEnabled(true);
            buttonModificar.setEnabled(true);
            textFieldNom.setText((String) tableDades.getValueAt(filaActual, 1));
            textFieldGenere.setText((String) tableDades.getValueAt(filaActual, 2));
            textFieldDescripcio.setText((String) tableDades.getValueAt(filaActual, 3));
            textFieldNumCapitols.setText(String.valueOf(tableDades.getValueAt(filaActual, 4)));
            textFieldDuracioCapitols.setText(String.valueOf(tableDades.getValueAt(filaActual, 5)));
            textFieldAnyEmissio.setText(String.valueOf(tableDades.getValueAt(filaActual, 6)));
            textFieldNota.setText(String.valueOf(tableDades.getValueAt(filaActual, 7)));
            if ((boolean) tableDades.getValueAt(filaActual, 8)) {
                checkBoxAcabat.setSelected(true);
            } else {
                checkBoxAcabat.setSelected(false);
            }
        }
    }//GEN-LAST:event_tableDadesMouseClicked

    private void buttonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserirActionPerformed
        Object[] options = {"Si", "No"};
        int opcio = JOptionPane.showOptionDialog(null, "Vols inserir aquestes dades?", null, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opcio == JOptionPane.YES_OPTION) {
            if (!dadesCorrectes()) {
                JOptionPane.showMessageDialog(this, "Dades incorrectes.");
                return;
            }
            if (casellaBuida == MAX_SERIES) {
                JOptionPane.showMessageDialog(this, "Nombre màxim d'entrades assolit.");
            } else {
                getArray()[casellaBuida].setNom(textFieldNom.getText().trim());
                getArray()[casellaBuida].setGenere(textFieldGenere.getText().trim());
                getArray()[casellaBuida].setDescripcio(textFieldDescripcio.getText().trim());
                getArray()[casellaBuida].setNumCapitols(Integer.valueOf(textFieldNumCapitols.getText()));
                getArray()[casellaBuida].setDuracioCapitols(Integer.valueOf(textFieldDuracioCapitols.getText()));
                getArray()[casellaBuida].setAnyEmissio(Integer.valueOf(textFieldAnyEmissio.getText()));
                getArray()[casellaBuida].setNota(Double.valueOf(textFieldNota.getText()));
                getArray()[casellaBuida].setAcabat(checkBoxAcabat.isSelected());
                getArray()[casellaBuida].setOmplert(true);
                casellaBuida++;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Operació cancel·lada.");
        }
        reiniciarFormulari();
    }//GEN-LAST:event_buttonInserirActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        Object[] options = {"Si", "No"};
        int opcio = JOptionPane.showOptionDialog(null, "Vols modificar aquestes dades?", null, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opcio == JOptionPane.YES_OPTION) {
            if (!dadesCorrectes()) {
                JOptionPane.showMessageDialog(this, "Dades incorrectes.");
                return;
            }
            int posicio = (int) tableDades.getValueAt(filaActual, 0);
            getArray()[posicio].setNom(textFieldNom.getText().trim());
            getArray()[posicio].setGenere(textFieldGenere.getText().trim());
            getArray()[posicio].setDescripcio(textFieldDescripcio.getText().trim());
            getArray()[posicio].setNumCapitols(Integer.valueOf(textFieldNumCapitols.getText()));
            getArray()[posicio].setDuracioCapitols(Integer.valueOf(textFieldDuracioCapitols.getText()));
            getArray()[posicio].setAnyEmissio(Integer.valueOf(textFieldAnyEmissio.getText()));
            getArray()[posicio].setNota(Double.valueOf(textFieldNota.getText()));
            getArray()[posicio].setAcabat(checkBoxAcabat.isSelected());
            getArray()[posicio].setOmplert(true);
        } else {
            JOptionPane.showMessageDialog(this, "Operació cancel·lada.");
        }
        reiniciarFormulari();
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        Object[] options = {"Si", "No"};
        int opcio = JOptionPane.showOptionDialog(null, "Segur que vols sortir del programa?", null, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opcio == JOptionPane.YES_OPTION) {
            int posicio = (int) tableDades.getValueAt(filaActual, 0);
            casellaBuida--;
            if (filaActual + 1 == MAX_SERIES) {
                getArray()[posicio].setOmplert(false);
            } else {
                for (int i = filaActual; i < casellaBuida; i++) {
                    getArray()[i] = getArray()[i + 1];
                }
                getArray()[casellaBuida] = new Serie();
                getArray()[casellaBuida].setOmplert(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Operació cancel·lada.");
        }
        reiniciarFormulari();
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortirActionPerformed
        Object[] options = {"Si", "No"};
        int opcio = JOptionPane.showOptionDialog(null, "Segur que vols sortir del programa?", null, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opcio == JOptionPane.YES_OPTION) {
            Projecte.finalitzar();
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(this, "Operació cancel·lada.");
        }
    }//GEN-LAST:event_buttonSortirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Projecte.finalitzar();
    }//GEN-LAST:event_formWindowClosing

    private void reiniciarFormulari() {
        textFieldNom.setText("");
        textFieldGenere.setText("");
        textFieldDescripcio.setText("");
        textFieldNumCapitols.setText("");
        textFieldDuracioCapitols.setText("");
        textFieldAnyEmissio.setText("");
        textFieldNota.setText("");
        checkBoxAcabat.setSelected(false);
        buttonEliminar.setEnabled(false);
        buttonModificar.setEnabled(false);
        metodeGUI.carregarTaula(new String[]{"Fila", "Nom", "Gènere", "Descripció", "Número de capítols", "Duració capítols: ", "Any d'emissió", "Nota", "Acabat"}, transformarDades(Projecte.getArray()), tableDades);
    }

    private boolean dadesCorrectes() {
        try {
            if (textFieldNom.getText().trim().equals("")) {
                throw new StringIndexOutOfBoundsException();
            }
            if (textFieldGenere.getText().trim().equals("")) {
                throw new StringIndexOutOfBoundsException();
            }
            if (textFieldDescripcio.getText().trim().equals("")) {
                throw new StringIndexOutOfBoundsException();
            }
            Integer.valueOf(textFieldNumCapitols.getText());
            Integer.valueOf(textFieldDuracioCapitols.getText());
            Integer.valueOf(textFieldAnyEmissio.getText());
            Double.valueOf(textFieldNota.getText());
        } catch (StringIndexOutOfBoundsException | NumberFormatException e) {
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_projecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_projecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_projecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_projecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_projecte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonInserir;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonSortir;
    private javax.swing.JCheckBox checkBoxAcabat;
    private javax.swing.JLabel labelAcabat;
    private javax.swing.JLabel labelAnyEmissio;
    private javax.swing.JLabel labelDescripcio;
    private javax.swing.JLabel labelDuracioCapitols;
    private javax.swing.JLabel labelGenere;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelNota;
    private javax.swing.JLabel labelNumCapitols;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JScrollPane scrollPaneTaula;
    private javax.swing.JTable tableDades;
    private javax.swing.JTextField textFieldAnyEmissio;
    private javax.swing.JTextField textFieldDescripcio;
    private javax.swing.JTextField textFieldDuracioCapitols;
    private javax.swing.JTextField textFieldGenere;
    private javax.swing.JTextField textFieldNom;
    private javax.swing.JTextField textFieldNota;
    private javax.swing.JTextField textFieldNumCapitols;
    // End of variables declaration//GEN-END:variables
}
